print('*'*70)
name = input("请输入姓名")
print('*'*70)
sex = input("请输入性别")
print('*'*70)
phone = input("请输入电话号码")
print('*'*70)
addr = input("请输入家庭住址")
print('*'*70)
email = input("请输入邮箱号码")
print("姓名%s\n 性别%s\n 电话号码%s\n 家庭住址%s\n 邮箱号码%s"%(name,sex,phone,addr,email))
